### ISSUE TITLE
Labels not showing up

### ISSUE THREAD

**Issue by dkoslicki** [jonathancrabtree/Circleator#27]
Following the instructions for [example 1](http://jonathancrabtree.github.io/Circleator/tutorials/coverage_plots.html), the resulting svg file does not display the labels (like 0.4 Kb, etc.).

**Comment by jonathancrabtree** [comment]
Do the labels show up when you rasterize the SVG to PNG or JPEG using the Apache Batik tools? If so then whatever tool you're using to view the SVG document may lack support for rendering text along a path. This was definitely the case in some older browsers, although if you have an up-to-date browser the SVG support is generally pretty good (except Safari where for some reason it is still very very slow!) You can also examine the SVG directly in a text editor and check to see whether the label text appears in the document.

**Comment by dkoslicki** [comment]
Yup, that appears to have fixed it! Just for the record, I was using ``rasterize-svg`` before fixing it with ``libbatik-java``. Thanks Jonathan

**Comment by jonathancrabtree** [comment]
That's interesting...so you're saying that the default system `rasterizer` command (a reference to which is hard-coded in `rasterize-svg`) couldn't handle text on paths? Can you tell me what O/S this was on?

**Comment by dkoslicki** [comment]
Argh, I typed too quickly. I was not using ``rasterize-svg`` before, I was using ``rsvg-convert`` as the system rasterizer (from Ubuntu 14.04.3's ``librsvg2-bin``). Sorry for the confusion.

**Comment by jonathancrabtree** [comment]
OK, thanks!
